// English side of the UI. Keyed by the Chinese literal itself rather than by an invented
// key: the source stays readable, a missing entry degrades to Chinese instead of blanking,
// and test_i18n_coverage can prove no literal is left untranslated.
//
// Keys must match the *runtime* string, so `\n` here is a real newline just as it is in the
// JSX it translates.
export const EN: Record<string, string> = {
  // ---- pipeline stages ----------------------------------------------------
  "切分": "Segment",
  "语音合成": "Voice",
  "拼接旁白": "Assemble",
  "分镜规划": "Storyboard",
  "字体子集": "Fonts",
  "生成画面": "Compose",
  "质检": "Lint",
  "渲染": "Render",
  "出片": "Deliver",

  // ---- nav / shell --------------------------------------------------------
  "呈现模式": "Modes",
  "呈现模式库": "Mode library",
  "先生成，再调整": "Generate first, adjust after",
  "——左边阶段流就是当前进度。": " — the stage flow on the left is the current progress.",
  "配置与逐拍编辑会在这一版出片后出现。": "Settings and per-beat editing appear once this version renders.",
  "还没有内容 — 粘贴一段文字，或点上面 ✨ 让 AI 从主题写一段。":
    "Nothing to work with — paste text, or press ✨ above to let AI draft from a topic.",
  "还没选配音音色。": "Pick a narration voice first.",
  "无法连接后端 — 服务还在跑吗？": "Cannot reach the backend — is the server still running?",
  "创建中…": "Creating…",
  "生成 ⌘↵": "Generate ⌘↵",

  // ---- AI script box ------------------------------------------------------
  "先给 AI 一个主题 — 它按主题写整段口播稿。":
    "Give AI a topic first — it writes the whole narration from it.",
  "给 AI 一个主题，自动生成旁白…": "Give AI a topic to draft the narration…",
  "✨ 生成": "✨ Draft",
  "生成中…": "Working…",
  "生成失败": "Generation failed",
  "模型已连通 ·": "Model connected ·",
  " · 本地 Ollama": " · local Ollama",
  "未检测到可用端点": "No usable endpoint found",
  "重新检测模型连通": "Re-check model connectivity",
  "检测中…": "Checking…",
  "重试": "Retry",
  "无法连接后端": "Cannot reach the backend",
  "✦ AI 写稿未启用 — 启动": "✦ AI drafting is off — run",
  "并拉取一个模型后点上面「重试」；或设": "and pull a model, then press Retry above; or point",
  "指向任意 OpenAI 兼容端点。也可直接粘贴文本。":
    "at any OpenAI-compatible endpoint. You can also paste text directly.",
  "需要模型连通": "Needs a connected model",
  "规则打底，模型只重判规则判成纯文字的拍":
    "Rules first; the model only re-judges beats the rules left as plain text",
  "模型加判": "Model assist",
  "纯规则": "Rules only",

  // ---- options ------------------------------------------------------------
  "画幅": "Aspect",
  "分镜": "Board",
  "分镜判定": "Storyboarding",
  "版式": "Layout",
  "极简": "Minimal",
  "杂志": "Editorial",
  "醒目": "Bold",
  "质量": "Quality",
  "草样": "Draft",
  "标准": "Standard",
  "高质": "Delivery",
  "帧率": "Frame rate",
  "格式": "Format",
  "导出格式": "Export format",
  "音色": "Voice",
  "旁白音色": "Narration voice",
  "配音": "Voiceover",
  "旁白": "Narration",
  "试听": "Audition",
  "试听当前音色": "Audition current voice",
  "停止试听当前音色": "Stop audition",
  "背景音乐": "Music",
  "外观": "Appearance",
  "外观 · 品牌": "Appearance · Brand",
  "品牌": "Brand",
  "品牌锁定处显示": "Shown where the brand lock-up sits",
  "强调色": "Accent",
  "默认": "Default",
  "预设名称": "Preset name",
  "载入预设…": "Loading preset…",
  "当前 Logo": "Current logo",
  "未设置": "Not set",
  "上传": "Upload",
  "载入中…": "Loading…",
  "移除": "Remove",
  "换图": "Replace",
  "更换": "Change",
  "外观未保存": "Appearance not saved",
  "无法保存外观 — 后端未响应": "Could not save appearance — backend not responding",
  "Logo 上传失败": "Logo upload failed",
  "保存": "Save",
  " · 保存中…": " · saving…",
  "取消": "Cancel",
  "对之后每个新作业生效；单个作业仍可在出片后到右侧调整。":
    "Applies to every new job afterwards; a single job can still be adjusted on the right after rendering.",
  "克制": "Restrained",
  "温暖": "Warm",
  "有力": "Punchy",
  "机智": "Witty",
  "短": "Short",
  "中": "Medium",
  "长": "Long",

  // ---- sample script ------------------------------------------------------
  "在漆黑的深海，超过九成的生物都能自己发光。\n这不是反射阳光，而是一场发生在体内的化学反应。":
    "In the lightless deep, more than ninety percent of living things make their own light.\n"
    + "It is not reflected sunlight — it is a chemical reaction happening inside the body.",

  // ---- studio -------------------------------------------------------------
  "节拍列表": "Beats",
  "属性面板": "Inspector",
  "选左侧一拍": "Select a beat on the left",
  "作业失败": "Job failed",
  "进行中…": "Running…",
  "渲染中…": "Rendering…",
  "· 重合成中…": "· recomposing…",
  "重排中…": "Reordering…",
  "← → 选拍 · ⇧←/→ 或拖动重排": "← → select · ⇧←/→ or drag to reorder",
  "编辑右侧即时更新预览；点 Render 出片": "Edit on the right and the preview updates live; hit Render to export",
  "真实画面进场": "Real frames incoming",
  "见下方日志": "see the log below",
  "字幕 SRT": "Captions SRT",
  "下载字幕 (SRT)": "Download captions (SRT)",
  "下载字幕 (WebVTT)": "Download captions (WebVTT)",
  "下载封面 (JPG)": "Download cover (JPG)",
  "封面": "Cover",
  "列表项": "List items",
  "流程节点": "Flow nodes",
  "分支节点（可逐个配截图）": "Branch nodes (each can hold a screenshot)",
  "环上节点": "Ring nodes",
  "漏斗层": "Funnel stages",
  "数据行": "Rows",
  "层（自上而下）": "Layers (top down)",
  "四个象限（按 01→04 顺序）": "Quadrants (in 01→04 order)",
  "卡片（名称 / 说明 / 配图）": "Cards (name / note / image)",
  "配图": "Image",
  "配图说明": "Caption",
  "图注": "Label",
  "给这张卡配图": "Add an image to this card",
  "给这个节点配截图": "Attach a screenshot to this node",
  "图片": "Image",
  "图片色调": "Image tone",
  "统一灰调": "Mono",
  "保留原色": "Keep colour",
  "图标": "Icon",
  "图标库": "Icon library",
  "无图标": "No icon",
  "无": "None",
  "没有匹配的图标": "No matching icons",
  "筛选图标…": "Filter icons…",

  // ---- setup --------------------------------------------------------------
  "Setup · 环境自检": "Setup · Environment",
  "重新检查 ↻": "Re-check ↻",
  "检查中…": "Checking…",
  "✓ 环境就绪，可以出片。": "✓ Environment ready — you can render.",
  "连不上后端。用": "Cannot reach the backend. Start it with",
  "启动后重试。": "and try again.",
  "GSAP (本地)": "GSAP (vendored)",
  "CJK 字体 (OFL)": "CJK font (OFL)",
  "无头 Chrome": "Headless Chrome",
  "渲染 sidecar": "Render sidecar",

  // ---- history ------------------------------------------------------------
  "还没有作业。点右上 new 开始。": "No jobs yet. Press new at the top right.",

  // ---- mode groups --------------------------------------------------------
  "文字与叙事": "Text & narrative",
  "清单与对照": "Lists & comparisons",
  "结构与图形": "Structure & diagrams",
  "数据可视化": "Data",
  "素材": "Media",
  "把一句话当成画面主角": "One sentence as the whole frame",
  "把并列内容排稳": "Line up parallel content",
  "关系画出来，不写出来": "Draw the relationship, don't describe it",
  "数字自己会说话": "Let the numbers speak",
  "相框 + 统一色调 + 缓慢推拉": "Frame + unified tone + slow push-in",

  // ---- modes: names -------------------------------------------------------
  "金句": "Statement",
  "章节": "Section",
  "术语": "Term",
  "收束": "Summary",
  "引言": "Quote",
  "文献卡": "Document",
  "旁注": "Note",
  "双栏": "Two column",
  "清单": "List",
  "对照": "Compare",
  "步骤": "Steps",
  "流程": "Flow",
  "导图": "Mind map",
  "循环": "Cycle",
  "漏斗": "Funnel",
  "分层": "Layers",
  "象限": "Quadrant",
  "条形": "Bars",
  "占比": "Share",
  "指标盘": "Metrics",
  "焦点数": "Big number",
  "趋势": "Trend",
  "时间轴": "Timeline",
  "数据表": "Table",
  "图片卡行": "Image row",
  "卡片": "Cards",

  // ---- modes: descriptions ------------------------------------------------
  "标签 + 大标题 + 副标题，开场第一帧": "Tag + headline + subtitle, the opening frame",
  "顶部短划 + 居中特大字号断言": "Rule on top, oversized assertion centred",
  "序号 + 标题，段落之间的分隔页": "Number + title, a divider between passages",
  "词条 + 释义，解释一个概念": "Term + definition, explaining one concept",
  "眉题 + 结语，用于一节或全片的落点": "Eyebrow + closing line, the landing of a section or the piece",
  "左竖线引出的引号段 + 出处": "Quoted passage off a left rule + attribution",
  "标签页纸卡 + 荧光笔高亮 + 落款": "Tabbed paper card + highlighter + signature",
  "标记符 + 一句补充说明": "Marker + one supporting line",
  "左侧提要撑住，右侧正文解释": "A takeaway holds the left, prose explains on the right",
  "标题 + 项目符号，逐条揭示": "Title + bullets, revealed one by one",
  "标题 + 名称/说明卡片行": "Title + a row of name/note cards",
  "左右两栏 + 中间分界": "Two columns with a divider between",
  "编号步骤，讲做法": "Numbered steps that say how",
  "节点顺序连接，讲链路": "Nodes linked in order — the chain",
  "中心概念放射分支，分支可带截图": "A hub radiating branches, which can carry screenshots",
  "节点坐在圆环上，讲闭环": "Nodes seated on a ring — the loop",
  "自上而下的层次堆叠": "A hierarchy stacked top down",
  "逐层收窄，宽度按真实数值": "Narrowing stage by stage, width from real values",
  "双轴 2×2 定位": "Two-axis 2×2 positioning",
  "横向条形排名，最大值为满格": "Horizontal bar ranking, max fills the track",
  "环形进度 + 百分比中心读数": "Ring gauge + percentage in the centre",
  "多个指标成格，各带涨跌": "Several metrics in a grid, each with a delta",
  "单个巨幅数字 + 单位 + 涨跌": "One oversized number + unit + delta",
  "迷你折线 + 峰值标注": "Sparkline + peak marker",
  "横轴刻度 + 错落事件": "Axis ticks + staggered events",
  "名称 + 数值，条形按最大值归一": "Name + value, bars normalised to the max",
  "并排的截图卡，各带名称与说明": "Screenshot cards side by side, each with a name and note",
  "搜模式（名称 / 用途）…": "Search modes (name / use)…",
  "没有匹配的模式": "No matching modes",
  "数值序列": "Value series",
  "漏斗层（自上而下）": "Funnel stages (top down)",
  "A 标题/描述": "A title/note",
  "B 标题/描述": "B title/note",
  "删除": "Delete",
  "切换界面语言": "Switch interface language",
  "模型未连通 · ": "Model unreachable · ",
  " 拍": " beats",
  "修复：": "Fix: ",
  "逐拍重新合成中（约 ": "Re-synthesising each beat (~ ",
  " 秒）…": "s)…",
  "全部 ": "All ",
  " 种": " modes",
  "每一拍选一种讲法。": "A different delivery for every beat. ",
  " 类 · 共 ": " groups · ",
  " 种，分镜会自动挑，也可以随时手动换。":
    " modes in total — the storyboard picks one, and you can swap any of them.",
};
